name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc
        package-manager-cache: false #https://github.com/actions/setup-node/issues/1357#issuecomment-3265614223
    
    - name: Enable corepack
      run: corepack enable
      shell: bash
    
    - name: Setup Node.js with cache
      uses: actions/setup-node@v5
      with:
        package-manager-cache: true
    
    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Install yarn for example
      run: cd example && yarn install
      shell: bash