name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-library:
    name: build-library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

  test-android-e2e:
    name: test-android-e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          cache: 'gradle'
          distribution: temurin
          java-version: 17

      - name: Write sitekeys to file
        env:
          EXAMPLE_ENV: ${{ secrets.EXAMPLE_ENV }}
        run: echo "$EXAMPLE_ENV" >> example/.env

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Build example for Android
        env:
          JAVA_OPTS: "-XX:MaxHeapSize=6g"
        run: |
          yarn example build:android
      
      - name: Get device name
        id: device
        run: |
          cd example
          node -e "console.log('AVD_NAME=' + require('./.detoxrc').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Detox build
        run: |
          cd example
          yarn detox build --configuration android.emu.release

      - name: Delete unnecessary tools 🔧
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          android: false 
          tool-cache: false
          dotnet: true 
          haskell: true 
          swap-storage: true 
          docker-images: false 
          large-packages: false
    
      - run: df -h

      - name: Pre-install Android Emulator System Image
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-28;default;x86_64" || true

      - name: E2E test for Android
        uses: reactivecircus/android-emulator-runner@a421e43855164a8197daf9d8d40fe71c6996bb0d # v2.38.0
        with:
          api-level: 28
          arch: x86_64
          avd-name: ${{ steps.device.outputs.AVD_NAME }}
          force-avd-creation: false
          emulator-boot-timeout: 1800
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none
          disable-animations: true
          script: cd example && yarn detox test --configuration android.emu.release --headless --record-logs all --record-videos failing --take-screenshots failing

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: detox-artifacts
          path: example/artifacts
          retention-days: 5

  test-ios-e2e:
    name: test-ios-e2e
    runs-on: macos-15-xlarge

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Select xcode version
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: '16.4'

      - name: Install macOS dependencies
        run: |
          brew install wix/brew/applesimutils || brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Write sitekeys to file
        env:
          EXAMPLE_ENV: ${{ secrets.EXAMPLE_ENV }}
        run: echo "$EXAMPLE_ENV" >> example/.env

      - name: Cache XCode Derived Data
        uses: irgaly/xcode-cache@4141f139f00e335c6e1031fb93e667181f86146f # v1.9.2
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-

      - name: Cache Example CocoaPods
        id: cache-example-cocoapods
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-example-pods-${{ hashFiles('example/ios/Podfile.lock') }}

      - name: Install Example CocoaPods # Need to still run pod install even with cache
        run: cd example/ios ; pod install

      - name: Build example for iOS
        run: |
          yarn example build:ios
    
      - name: Detox rebuild framework cache
        run: |
          cd example
          yarn detox rebuild-framework-cache

      - name: Detox build
        run:  |
          cd example
          yarn detox build --configuration ios.sim.release

      - name: Detox test
#        continue-on-error: true # iOS test is flaky, run locally for now
        run:  |
          cd example
          yarn detox test --configuration ios.sim.release --headless --record-logs all --record-videos failing --take-screenshots failing

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: detox-artifacts
          path: example/artifacts
          retention-days: 5
